version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 100.98.26.42:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
