route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Ajeet_Raina'
            channel: '#collabnixworld'
            api_url: 'https://hooks.slack.com/services/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'
